# Generated by Django 2.0.7 on 2018-07-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.NullBooleanField(default=None)),
                ('likes', models.IntegerField(default=0)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
